<?php echo $this->doctype() ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <script type="text/javascript">


                var baseUrl = "<?php echo $this->baseUrl(); ?>";
        
        </script>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/ui/jquery-ui-1.8rc3.custom.css') ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/layout.css') ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/forms.css') ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/text.css') ?>

<?php echo $this->cssHelper() ?>   
<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.4.2.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8rc3.custom.min.js') ?> 
<?php $this->headScript()->appendFile($this->baseUrl().'/js/DD_roundies_0.0.2a.js') ?> 
<?php $this->headScript()->appendFile($this->baseUrl().'/js/functions.js') ?> 


<?php $this->javascriptHelper() ?>
<?php echo $this->headScript() ?> 
<?php echo $this->headTitle() ?>

</head>
<body>  
    <div id="head1"></div><div id="head2"></div>
	<div id="Wrapper">
	
	<div id="Header">
        <div id="Logo">
           <a href="<?php echo $this->baseUrl();?>"> 
           	<img src="<?php echo $this->baseUrl('img/aonLogo.gif');?>" alt="Logo"/>
           </a>
        </div>
	<?php echo $this->profileHelper();?>
    </div>
