<?php
	list($read,$add,$modify,$delete) = explode(",",$this->rights,10);
	
	if($read != "r")
		header('Location:'.$this->baseUrl('index/index'));
?>
<div id="contentLeft">

<h2> Conturi de Acces </h2>
<hr/>

<!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Utilizatori</h2>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<form action="#">
			<fieldset>
			<!--[if !IE]>start table_wrapper<![endif]-->
			<div class="table_wrapper">
				<div class="table_wrapper_inner">
				<table cellpadding="0" cellspacing="0" width="100%">
					<tbody><tr>
						<th>Numar.</th>
						<th><a href="#">Nume Utilizator</a></th>
						<th><a href="#">Username</a></th>
						<th><a href="#" class="asc">Rol</a></th>
						<th><a href="#" class="asc">Email</a></th>
						<th style="width: 96px;">Actiuni</th>
					</tr>
					<?php 
						$i = 1;
						foreach($this->rows as $row)   
						{		
					?>
					<tr class="first">
						<td ><?php echo $i."."; ?></td>
						<td><?php echo $row['name'];?></td>
						<td><?php echo $row['username'];?></td>
						<td><?php echo $this->roles[$i];?></td>
						<td><?php echo $row['email'];?></td>
						<td style="width: 96px;">
							<div class="actions">
								<ul>
									<?php if($modify == "m"){ ?>
									<li><a class="action2" id="<?php echo $row['id']; ?>"  href="<?php echo $this->baseUrl('index/edituser/id/'.$row['id']); ?>">2</a></li>
									<?php } ?>
									<!-- <li><a class="action3" href="#">3</a></li> -->
									<?php if($delete == "d" && $row['id'] != '1'){ ?>
										<li><a class="action4" id="<?php echo $row['id']; ?>" onclick="return deleteSelectedUser(this)" href="javascript: void(0);">4</a></li>
									<?php }?>
									<?php if($row['id'] != '1') { ?>
										<li><input class="radio" id="<?php echo $row['id']; ?>" name="" type="checkbox" value="" /></li>
									<?php } ?>
								</ul>
							</div>
						</td>
					</tr>
					<?php $i++; }?>
				</tbody></table>
				</div>
			</div>
			<!--[if !IE]>end table_wrapper<![endif]-->
			
			<!--[if !IE]>start table menu<![endif]-->
			<div class="table_menu">
				<?php if($add == "a"){ ?>
				<ul class="left">
					<li><a href="<?php echo $this->baseUrl('index/adduser') ?>" class="button add_new"><span><span>Adauga Utilizator</span></span></a></li>
				</ul>
				<?php } ?>
				<ul class="right">
					<li><span onclick="checkAll();" class="button approve"><span><span>Selecteaza Tot</span></span></span></li>
					<li><span onclick="uncheckAll();" class="button approve"><span><span>Deselecteaza Tot</span></span></span></a></li>
					<?php if($delete == "d"){ ?>
					<li><span onclick="deleteSelectedUsers()" class="button approve"><span><span>Sterge Selectate</span></span></span></li>
					<?php } ?>
				</ul>
			</div>
			<!--[if !IE]>end table menu<![endif]-->
			
			
			</fieldset>
			</form>
		
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->
 	 	
</div>

