 <?php
	list($read,$add,$modify,$delete) = explode(",",$this->rights,10);
	
	if($read != "r")
		header('Location:'.$this->baseUrl('index/index'));
?>
<script>
	function setProductive()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
				
				if(!isNaN(v.id)){
					categories.push(v.id);
					count = count+1;
				}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'productive' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}
	
	function setUnproductive()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
			if(!isNaN(v.id)){
				categories.push(v.id);
				count = count+1;
			}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'unproductive' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}
	
	function setUnclassified()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
			if(!isNaN(v.id)){
				categories.push(v.id);
				count = count+1;
			}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'unclassified' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}		
</script>
<div id="contentLeft">

<h2> Site-uri ( Aplicatii Productive / Neproductive ) </h2>
<hr/>

<!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Lista Site-uri</h2>
		<span class="title_wrapper_left"></span>
		<span class="title_wrapper_right"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<div class="sct_left">
				<div class="sct_right">
					<div class="sct_left">
						<div class="sct_right">
							<form action="#">
							<fieldset>
							<!--[if !IE]>start table_wrapper<![endif]-->
							<div class="table_wrapper">
								<div class="table_wrapper_inner">
								<table cellpadding="0" cellspacing="0" width="100%">
									<tbody><tr>
										<th width="3%">Numar.</th>
										<th>Nume</th>
										<th>Tip</a></th>
										<th>Categorie</th>
										<th style="width: 96px;">Actiuni</th>
									</tr>
									<?php 
										$i = 1;
										foreach($this->sites as $category)   
										{		
									?>
									<tr class="first">
										<td ><?php echo $i."."; ?></td>
										<td><?php echo $category['name'];?></td>
										<td><?php echo $category['type'];?></td>
										<td><?php echo $category['category'];?></td>
									
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<?php if($modify == "m"){ ?>
													<li><a class="action2" id="<?php echo $category['id']; ?>"  href="<?php echo $this->baseUrl('index/editcategory/id/'.$category['id'])."/category/".$category['category']; ?>">2</a></li>
													<?php } ?>
													<?php if($delete == "d"){ ?>
													<li><a class="action4" id="<?php echo $category['id']; ?>" onclick="return deleteSelectedCategory(this)" href="javascript: void(0);">4</a></li>
													<?php }?>
													<li><input class="radio" id="<?php echo $category['id']; ?>" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<?php $i++; }?>
								</tbody></table>
								</div>
							</div>
							<!--[if !IE]>end table_wrapper<![endif]-->
							
							<!--[if !IE]>start table menu<![endif]-->
							<div class="table_menu">
								<ul class="right">
									<li><span onclick="checkAll();" class="button approve"><span><span>Selecteaza Tot</span></span></span></li>
									<li><span onclick="uncheckAll();" class="button approve"><span><span>Deselecteaza Tot</span></span></span></a></li>
									<?php if($delete == "d"){ ?>
									<li><span onclick="deleteSelectedCategories()" class="button approve"><span><span>Sterge Selectate</span></span></span></li>
									<?php } ?>
									<?php if($modify == "m"){ ?>
									<li><a href="javascript:void(0)" onclick="setProductive()"class="button add_new"><span><span>Productiv</span></span></a></li>
									<li><a href="javascript:void(0)" onclick="setUnproductive()"class="button add_new"><span><span>Neproductiv</span></span></a></li>
									<li><a href="javascript:void(0)" onclick="setUnclassified()"class="button add_new"><span><span>Neclasificat</span></span></a></li>
									<?php } ?>									
								</ul>
							</div>
							<!--[if !IE]>end table menu<![endif]-->
							
							
							</fieldset>
							</form>
							
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		<!--[if !IE]>start section content bottom<![endif]-->
		<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
		<!--[if !IE]>end section content bottom<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->
 	 	


</div>