<?php
	list($read,$add,$modify,$delete) = explode(",",$this->rights,10);
	
	if($read != "r")
		header('Location:'.$this->baseUrl('index/index'));
?>

<script>
	function setProductive()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
				
				if(!isNaN(v.id)){
					categories.push(v.id);
					count = count+1;
				}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'productive' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}
	
	function setUnproductive()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
			if(!isNaN(v.id)){
				categories.push(v.id);
				count = count+1;
			}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'unproductive' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}
	
	function setUnclassified()
	{
		var categories = new Array();
		var count = 0;
		$.each($('input:checked'), function(k, v) {
			if(!isNaN(v.id)){
				categories.push(v.id);
				count = count+1;
			}
		});
		if(count == 0 )
		{
			alert("Nu ati selectat nici un user");
		}
		else{
			$.ajax({
                type : "POST",
                url : "<?php echo $this->baseUrl('index/settypecategories'); ?>",
                data: {categories: categories, type:'unclassified' },
                dataType : "json",
                success : function(data) {               
                    window.location.reload();
                }
     	   });		
 	   }	
	}		
</script>

<div id="contentLeft">

<h2> Categorii ( Aplicatii Productive / Neproductive ) </h2>
<hr/>

<!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Lista Categorii</h2>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<form action="#">
			<fieldset>
			<!--[if !IE]>start table_wrapper<![endif]-->
			<div class="table_wrapper">
				<div class="table_wrapper_inner">
				<table cellpadding="0" cellspacing="0" width="100%">
					<tbody><tr>
						<th width="3%">Numar.</th>
						<th>Nume</th>
						<th>Tip</a></th>
						<th>Categorie</th>
						<th style="width: 96px;">Actiuni</th>
					</tr>
					<?php 
						$i = (($this->currentPage - 1 )*$this->rowsPerPage) + 1;
						foreach($this->categories as $category)   
						{		
					?>
					<tr class="first">
						<td ><?php echo $i."."; ?></td>
						<td><?php 
							if($category['category'] == 'site')
								echo "<a href = 'http://".$category['name']."' target='_blank'>".$category['name']."</a>";
							else
								echo $category['name'];?></td>										

						<td><?php echo $category['type'];?></td>
						<td><?php echo $category['category'];?></td>
					
						<td style="width: 96px;">
							<div class="actions">
								<ul>
									<?php if($modify == "m" && !in_array($category['name'],$this->notSet)){ ?>
									<li><a class="action2" id="<?php echo $category['id']; ?>"  href="<?php echo $this->baseUrl('index/editcategory/id/'.$category['id'])."/category/".$category['category']; ?>">2</a></li>
									<?php } ?>
									<?php if($delete == "d"){ ?>
									<!-- <li><a class="action4" id="<?php echo $category['id']; ?>" onclick="return deleteSelectedCategory(this)" href="javascript: void(0);">4</a></li>  -->
									<?php }?>
									<?php  if(!in_array($category['name'],$this->notSet)){ ?>
									<li><input class="radio" id="<?php echo $category['id']; ?>" name="" type="checkbox" value="" /></li>
									<?php }?>
								</ul>
							</div>
						</td>
					</tr>
					<?php $i++; }?>
				</tbody></table>
				</div>
			</div>
			<!--[if !IE]>end table_wrapper<![endif]-->
			
			<!--[if !IE]>start table menu<![endif]-->
			<div class="table_menu">
				<ul class="right">
					<li><span onclick="checkAll();" class="button approve"><span><span>Selecteaza Tot</span></span></span></li>
					<li><span onclick="uncheckAll();" class="button approve"><span><span>Deselecteaza Tot</span></span></span></a></li>
					<?php if($delete == "d"){ ?>
					<!--  <li><span onclick="deleteSelectedCategories()" class="button approve"><span><span>Sterge Selectate</span></span></span></li>  -->
					<?php } ?>
					<?php if($modify == "m"){ ?>
					<li><a href="javascript:void(0)" onclick="setProductive()"class="button add_new"><span><span>Productiv</span></span></a></li>
					<li><a href="javascript:void(0)" onclick="setUnproductive()"class="button add_new"><span><span>Neproductiv</span></span></a></li>
					<li><a href="javascript:void(0)" onclick="setUnclassified()"class="button add_new"><span><span>Neclasificat</span></span></a></li>
					<?php } ?>
				</ul>
			</div>
			<!--[if !IE]>end table menu<![endif]-->
			
			
			</fieldset>
			</form>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<div id="pagination">
	
	<div id="pageNumber">
		<?php echo $this->currentPage." / ".$this->totalPages." "; ?> Pages
	</div>
	<div id="navigation">
		<?php if($this->currentPage-1){ ?>
		<a href="<?php
			echo $this->baseUrl('index'.$this->currentURL.'/p/'.($this->currentPage-1)); ?>"><b>Previous</b></a>
		<?php } else  {  ?> 
			<b>Previous</b>
		 <?php } ?>
	
	<?php if($this->currentPage != $this->totalPages){ ?>	
	 <a href="<?php echo $this->baseUrl('index'.$this->currentURL.'/p/'.($this->currentPage+1)); ?>"><b><span style="padding-left:7px;">Next</span></b></a>
	 <?php } else { ?>
	 	<b><span style="padding-left:7px;">Next</span></b>
	 <?php } ?>
	</div>
	
</div>
<!--[if !IE]>end section<![endif]-->
 	 	
</div>

