
<div id="contentLeft">
<script>
	function goBack()
	{
		window.location='<?php echo $this->baseUrl('index/home') ?>';
	}
</script>
	<div class="sct" style="padding:10px; float:left;">
		<h2> Schimbare parola<button style="margin-left:10px;" onClick="goBack()"> Renunta </button> </h2>
		<hr/>
		<div id="left" style="display:inline;float:left;" >
			<?php
				echo $this->form;
			 ?>
		</div>
	</div>	
</div>