<div id="contentLeft">
 	 <h2>Drepturi Utilizator
 	 	<hr/>
 	 	
 	 <?php 
	   if(!empty($this->user)) 
				echo "Logat"."</br>"; 
		else
			echo "Username si Password invalide"; ?>
 	 <!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Utilizatori</h2>
		<span class="title_wrapper_left"></span>
		<span class="title_wrapper_right"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<div class="sct_left">
				<div class="sct_right">
					<div class="sct_left">
						<div class="sct_right">
							<form action="#">
							<fieldset>
							<!--[if !IE]>start table_wrapper<![endif]-->
							<div class="table_wrapper">
								<div class="table_wrapper_inner">
								<table cellpadding="0" cellspacing="0" width="100%">
									<tbody><tr>
										<th>Numar.</th>
										<th><a href="#">Nume</a></th>
										<th><a href="#" class="asc">Rol</a></th>
										<th><a href="#" class="asc">Departament</a></th>
										<th><a href="#">Ultima Inregistrare</a></th>
										<th style="width: 96px;">Actiuni</th>
									</tr>
									<tr class="first">
										<td>1.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>2.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
								<tr class="first">
										<td>3.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>4.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
								   <tr class="first">
										<td>5.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>6.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
								<tr class="first">
										<td>7.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>8.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
								<tr class="first">
										<td>9.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>10.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>	
								<tr class="first">
										<td>11.</td>
										<td>Ionescu Popescu</td>
										<td>Manager</td>
										<td>HR</td>
										<td>06/18/2011</td>
										<td style="width: 96px;">
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>
									<tr class="second">
										<td>12.</td>
										<td>Ionescu Vasilescu</td>
										<td>Admin</td>
										<td>IT</td>
										<td>01/09/2011</td>
										<td>
											<div class="actions">
												<ul>
													<li><a class="action1" href="#">1</a></li>
													<li><a class="action2" href="#">2</a></li>
													<li><a class="action3" href="#">3</a></li>
													<li><a class="action4" href="#">4</a></li>
													<li><input class="radio" name="" type="checkbox" value="" /></li>
												</ul>
											</div>
										</td>
									</tr>	
								</tbody></table>
								</div>
							</div>
							<!--[if !IE]>end table_wrapper<![endif]-->
							
							<!--[if !IE]>start table menu<![endif]-->
							<div class="table_menu">
								<ul class="left">
									<li><a href="#" class="button add_new"><span><span>Adauga Utilizator</span></span></a></li>
								</ul>
								<ul class="right">
									<li><a href="#" class="button check_all"><span><span>Selecteaza Tot</span></span></a></li>
									<li><a href="#" class="button uncheck_all"><span><span>Deselecteaza Tot</span></span></a></li>
									<li><span class="button approve"><span><span>Accepta</span></span></span></li>
								</ul>
							</div>
							<!--[if !IE]>end table menu<![endif]-->
							
							
							</fieldset>
							</form>
							
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		<!--[if !IE]>start section content bottom<![endif]-->
		<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
		<!--[if !IE]>end section content bottom<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->

</div>