<?php
	list($read,$add,$modify,$delete) = explode(",",$this->rights,10);
	
	if($read != "r")
		header('Location:'.$this->baseUrl('index/index'));
		
?>

<div id="contentLeft">
 	 <h2>Angajati</h2>
 	 <hr/>

<!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Angajati</h2>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<form action="#">
			<fieldset>
			<!--[if !IE]>start table_wrapper<![endif]-->
			<div class="table_wrapper">
				<div class="table_wrapper_inner">
				<table cellpadding="0" cellspacing="0" width="100%">
					<tbody><tr>
						<th width="5%">Numar.</th>
						<th>Utilizatori Windows Monitorizati</th>
						<th>Nume</th>
						<th>Prenume</th>
						<th>Departament</th>
						<th style="width: 96px;">Actiuni</th>
					</tr>
					<?php 
						$i = 1;
						foreach($this->rows as $row)   
						{
							if(!empty($row['id']))
							{
								$id = $row['id'];
							}
							else
							{
								$id = 0;
							}
							
							if(!empty($row['idFromServer']))
							{
								$idFromServer = $row['idFromServer'];
							}
							else
							{
								$idFromServer = 0;
							}
					?>
					<tr class="first">
						<?php if(!empty($row)){ ?>
						<td ><?php echo $i."."; ?></td>
						<td><?php echo $row['name'];?></td>
						<td><?php echo empty($row['last_name'])?'':$row['last_name'];?></td>
						<td><?php echo empty($row['first_name'])?'':$row['first_name']; ?></td>
						<td><?php  if(empty($row['department']))
										echo "Departament sters";
								   else
										echo $row['department'];
						?></td>
						
						<td style="width: 96px;">
							<div class="actions">
								<ul>
									<?php if($modify == "m"){ ?>
									<li><a class="action2" id="<?php echo $row['idFromServer']; ?>"  href="<?php echo $this->baseUrl('index/editusertodept/id/'.$id.'/idfromserver/'.$row['name']); ?>">2</a></li>
									<?php } ?>
									<?php if($delete == "d"){ ?>
										<!-- <li><a class="action4" id="<?php echo $row['idFromServer']; ?>" onclick="return deleteSelectedDepartment(this)" href="javascript: void(0);">4</a></li> -->
									<?php }?>
										<!-- <li><input class="radio" id="<?php echo $row['idFromServer']; ?>" name="" type="checkbox" value="" /></li> -->
								</ul>
							</div>
						</td>
						<?php } ?>
					</tr>
					<?php $i++; }?>
				</tbody></table>
				</div>
			</div>
			<!--[if !IE]>end table_wrapper<![endif]-->
			
			<!--[if !IE]>start table menu<![endif]-->
			<div class="table_menu">
				<ul class="right">
					<!--<li><span onclick="checkAll();" class="button approve"><span><span>Selecteaza Tot</span></span></span></li>
					<li><span onclick="uncheckAll();" class="button approve"><span><span>Deselecteaza Tot</span></span></span></a></li> -->
				</ul>
			</div>
			<!--[if !IE]>end table menu<![endif]-->
			
			
			</fieldset>
			</form>
							
					
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->
 		 	
</div>