<div id="contentLeft">
    <?php echo $this->pageCategoryOffers; ?>
</div>
<div id="contentMiddle" class="mainContent">
    <?php echo $this->pageContent['page_resources_right']; ?>
    <?php echo $this->pageContactForm; ?>
</div>
<div id="contentRight">
    <div id="populairOffersHeader"><?php echo $this->languageHelper('populairoffers'); ?></div>
    <?php echo $this->pagePopulairOffers; ?>
</div>
