<?php
$usersToDepartments = $this->usersToDepartments;
$departments = $this->departments;
//echo "<pre>"; print_r($this->usersToDepartments);echo "</pre>";
//echo "<pre>"; print_r($this->departments);echo "</pre>";die();
$status = array();
$statusUser = array();
$usersMonitorized = $this->usersMonitorized;
$departmentsMonitorized = $this->deptBanned;

function hasChildsDepartments($parent,$departments)
{
	foreach($departments as $department)
	{
		if($department['id'] == $parent)
			return 1;
	}
	return 0;
}

function hasChildsUsers($parent,$usersToDepartments)
{
	foreach($usersToDepartments as $user)
	{
		if($user['department'] == $parent)
			return 1;
	}
	return 0;
}

function printUsersWithDept($department,$usersToDepartments,$usersMonitorized)
{
	global $statusUser;
	$statusUser[$department] = "1";
	foreach($usersToDepartments as $user)
	{
		//echo $department;echo "</br>";
		// print_r($user);die();
		
		if($user['department'] == $department)
			if (in_array($user['id'], $usersMonitorized)){		
				echo "<li class=\"organigramaUser\" id=\"{$user['name']}\">
	                                <span class'file'>
	                                    <input class=\"userselector\" type=\"checkbox\" id=\"".$user['name']."\"> {$user['name']}
	                                </span></li>";
			}
	}
}

function printDepartment($parent,$departments,$usersToDepartments,$usersMonitorized,$departmentsMonitorized)
{
	global $status,$statusUser;
	$gasit = 0;
	foreach($departments as $department)
	{

		if($department['parent'] == $parent && empty($status[$department['id']]))
		{
			$gasit = 1;
			if(empty($departmentsMonitorized[$department['parent']]))
			{			
				if(empty($statusUser[$department['parent']]))
					printUsersWithDept($department['parent'],$usersToDepartments,$usersMonitorized);
			}
			if(empty($departmentsMonitorized[$department['id']])){			
				if(hasChildsDepartments($department['id'],$departments))
				{
					echo "<li>";
					echo "<span class='folder'>
	                                        <input class=\"deptselector\" type=\"checkbox\" id=\"".$department['name']."\"/> ".$department['name']."</span>
	                                        <ul>";
					//printUsersWithDept($department['id'],$usersToDepartments);
					$status[$department['id']] = "1";
					printDepartment($department['id'],$departments,$usersToDepartments,$usersMonitorized,$departmentsMonitorized);
					echo "";
				}
				else
				{
					echo "<li>
	                                        <span class='folder'><input class=\"deptselector\" type=\"checkbox\" id=\"".$department['name']."\"/> ".$department['name']."</span>
	                                    </li>";
					//printUsersWithDept($department['id'],$usersToDepartments);
					$status[$department['id']] = "1";
					
				}
				echo "</li></ul>";
			}
		}
		
	}	

	if($gasit == 0)
	{
		printUsersWithDept($parent, $usersToDepartments,$usersMonitorized,$departmentsMonitorized);
	}
}

 function startTree($parent,$departments,$usersToDepartments,$status,$usersMonitorized,$departmentsMonitorized)
 {
 	global $status;
 	foreach($departments as $department)
	{
		if(empty($status[$department['id']]))
		{
			printDepartment($department['id'],$departments,$usersToDepartments,$usersMonitorized,$departmentsMonitorized);
			//printUsersWithDept($department['id'],$usersToDepartments);
			//$status[$department['id']] = $department['id'];
		}
	}
	
 }
 
 ?>
 
<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Productivo Admin Panel</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('img/productivo_icon_tiny.jpg')?>">
        <!-- START Load CSS/JScript -->
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/admin.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/reset.css')); ?>
		<?php $this->headLink()->prependStylesheet($this->baseUrl('css/tipTip.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/jquery.treeview.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/components.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/datatables/jquery.dataTables.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/components.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl('css/smoothness/jquery-ui-1.8.18.custom.css')); ?>
        <?php echo $this->cssHelper() ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/amcharts.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery.tipTip.minified.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/lib/jquery.cookie.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery.treeview.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/raphael.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/elycharts.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/default/objects/divButton.js')); ?>
        <?php //$this->headScript()->prependFile($this->baseUrl('js/default/objects/siteOffers.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/default/objects/contactForm.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/default/objects/googleMap.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/cufonNow.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('fonts/Helvetica_400-Helvetica_400.font.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/cufon.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery.timepicker.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery.dataTables.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery-ui-1.8.14.js')); ?>
        <?php $this->headScript()->prependFile($this->baseUrl('js/jquery-1.6.2.js')); ?>        
        <?php $this->javascriptHelper() ?>
        <?php echo $this->headScript() ?>
        <!--[if gte IE 9]>
        <script type="text/javascript">
        Cufon.set('engine', 'canvas');
        </script>
        <![endif]-->
        <!-- END Load CSS/JScript -->
        <script type="text/javascript">
           $(document).ready(function(){
        	   for(var i=1; i<=13; i++)
					$("#d" + i).tipTip({delay:0});
				$("#organigrama").treeview({
					animated:"normal",
					persist: "cookie"
				});
			});
        </script>

	<?php //echo "<pre>"; print_r($this->usersToDepartments);die();echo "</pre>"; ?>
	<?php foreach ($this->departments as $department)
				if( $department['parent'] == 0 )
					$root = "<input class=\"deptselector\" type=\"checkbox\" id=\"".$department['name']."\"/> ".$department['name'];
		//printDepartment("1",$departments,$usersToDepartments);die();
		//startTree("0",$departments,$usersToDepartments,$status);die();
	 ?>
    </head>
    <body rel="<?php echo $this->baseUrl('public/../'); ?>">
        <!--[if !IE]>start wrapper<![endif]-->
	<div id="wrapper">
		<!--[if !IE]>start head<![endif]-->
		<div id="head">
			<div id="banda_head">
				<div id="logo"></div>
				
				<!--[if !IE]>start menus_wrapper<![endif]-->
				
				<div id="menus_wrapper">
					<ul id="main_menu">
						<li><a href="<?php echo $this->baseUrl('/index/rapoarte'); ?>" ><img id="rapoarte" src="<?php echo $this->baseUrl('img/rapoarte_active.png'); ?>" /></a></li>
						<li><a href="<?php echo $this->baseUrl('/index/home'); ?>" onmouseover="changeSrc('<?php echo $this->baseUrl('img/administrare_over.png'); ?>', 'administrare')" onmouseout="changeSrc('<?php echo $this->baseUrl('img/administrare.png'); ?>', 'administrare')" onmousedown="changeSrc('<?php echo $this->baseUrl('img/administrare_down.png'); ?>', 'administrare')" onmouseup="changeSrc('<?php echo $this->baseUrl('img/administrare.png'); ?>', 'administrare')" ><img id="administrare" src="<?php echo $this->baseUrl('img/administrare.png'); ?>" /></a></li>
						<li><a href="#" onmouseover="changeSrc('<?php echo $this->baseUrl('img/ajutor_over.png'); ?>', 'ajutor')" onmouseout="changeSrc('<?php echo $this->baseUrl('img/ajutor.png'); ?>', 'ajutor')" onmousedown="changeSrc('<?php echo $this->baseUrl('img/ajutor_down.png'); ?>', 'ajutor')" onmouseup="changeSrc('<?php echo $this->baseUrl('img/ajutor.png'); ?>', 'ajutor')" ><img id="ajutor" src="<?php echo $this->baseUrl('img/ajutor.png'); ?>" /></a></li>
					</ul>
					<ul id="user_access">
						<a href="<?php echo $this->baseUrl('index/changepassword') ?>"><li>Change Password |</li></a>
						<a href="<?php echo $this->baseUrl('index/logout') ?>"><li class="last">Log out</li></a>
					</ul>
				</div>
				
				
				<!--[if !IE]>end menus_wrapper<![endif]-->
			</div>
		</div>
		<!--[if !IE]>end head<![endif]-->
		
		<!--[if !IE]>start content<![endif]-->
        <!-- START Content -->
		
		<div id="content">
			<div id="banda_rosie">
				<ul id="left_reports">
					<?php foreach($this->reportMonitor as $item){ ?>
						<li><a onmouseover="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '_over.png'; ?>','<?php echo $item['class']; ?>')" onmouseout="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>','<?php echo $item['class']; ?>')" onmousedown="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '_active.png'; ?>','<?php echo $item['class']; ?>')" onmouseup="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>','<?php echo $item['class']; ?>')" href="<?php echo $this->baseUrl('index/'.$item['page']); ?>" ><img title="<?php echo $item['full_name']; ?>" id="<?php echo $item['class']; ?>" src="<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>" /></a></li>
					<?php } ?>	
				</ul>
				<ul id="right_reports">
					<?php foreach($this->reportActivity as $item){ ?>
						<li><a onmouseover="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '_over.png'; ?>','<?php echo $item['class']; ?>')" onmouseout="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>','<?php echo $item['class']; ?>')" onmousedown="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '_active.png'; ?>','<?php echo $item['class']; ?>')" onmouseup="changeSrc('<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>','<?php echo $item['class']; ?>')" href="<?php echo $this->baseUrl('index/'.$item['page']); ?>" ><img title="<?php echo $item['full_name']; ?>" id="<?php echo $item['class']; ?>" src="<?php echo $this->baseUrl('img/dasboard_icons/') . $item['class'] . '.png'; ?>" /></a></li>
					<?php } ?>
				</ul>
			</div>
					
			<!--[if !IE]>start section<![endif]-->	
			<div id="content_wrapper">
				<div class="section_o">
				<!--[if !IE]>start title wrapper<![endif]-->
				<div class="title_wrapper">
					<h2>Organigrama</h2>
				</div>
				<!--[if !IE]>end title wrapper<![endif]-->
				<!--[if !IE]>start section content<![endif]-->
				<div class="section">
					<!--[if !IE]>start section content top<![endif]-->
					<div class="sct">
						<ul id="organigrama" class="filetree" style="vertical-align:text-bottom;height: 400px;overflow: scroll;">
							<li>
								<span class="folder"><?php echo $root; ?></span>
								<ul>
									<?php startTree("0",$departments,$usersToDepartments,$status,$usersMonitorized,$departmentsMonitorized); ?>
								</ul>
							</li>
						</ul>		
					</div>
					<!--[if !IE]>end section content top<![endif]-->
				
					
				</div>
				<!--[if !IE]>end section content<![endif]-->
                                <!-- div id="orgSelectedContainer" style="display:none;text-align:center;">
                                    Utilizator selectat:<br/>
                                    <span id="orgSelectedUser" style="font-weight:bold;"></span><br/><br/>
                                    <input type="button" value="Sterge filtrul" id="orgSelectedClear" />
                                </div -->
				</div>	
			
			<!--[if !IE]>end section<![endif]-->
			<!--[if !IE]>start section<![endif]-->	
			<div class="section_t">
				<!--[if !IE]>start title wrapper<![endif]-->
				<div class="title_wrapper">
					<h2>Timp</h2>
				</div>
				<!--[if !IE]>end title wrapper<![endif]-->
				<!--[if !IE]>start section content<![endif]-->
				<div class="section">
					<!--[if !IE]>start section content top<![endif]-->
					<div class="sct">
						<?php echo $this->layout()->content; ?>
						<br style="clear: both;" />
					</div>
					<!--[if !IE]>end section content top<![endif]-->
				
					
				</div>
				<!--[if !IE]>end section content<![endif]-->
			</div>
			<!--[if !IE]>end section<![endif]-->
			</div>						
			<div id="clear"></div>
            <div id="report_page">
				<div class="inner">
                
                </div>
            </div>
			
			
		</div>
		<!--[if !IE]>end content<![endif]-->
		
	</div>
	<!--[if !IE]>end wrapper<![endif]-->
	
	<!--[if !IE]>start footer<![endif]-->
	<div id="footer">
		<div id="footer_inner">
		
		<dl class="copy">
			<dt><strong>Productivo Admin</strong></dt>
			<dd>&copy; 2012 Productivo.ro  All rights reserved.</dd>
		</dl>
		
		<dl class="quick_links">
			<dt><strong>Quick Links :</strong></dt>
			<dd>
				<ul>
					<li><a href="#">Administrare </a></li>
					<li><a href="#">Rapoarte</a></li>
					<li><a href="#">Ajutor</a></li>
					<li class="last"><a href="#">Log out</a></li>
				</ul>
			</dd>
		</dl>
		
		
		<dl class="help_links">
			<dt><strong>Ai nevoie de ajutor?</strong></dt>
			<dd>
				<ul>
					<li><a href="#">FAQ</a></li>
					<li class="last"><a href="#">Contact</a></li>
				</ul>
			</dd>
		</dl>
	
		</div>
	</div>
	<!--[if !IE]>end footer<![endif]-->
	<script type="text/javascript">
	function changeSrc(path,id)
	{
		document.getElementById(id).src = path;
	}
	</script>
</body>
</html>
<script type="text/javascript">
    
    $(document).ready(function() {
      
        $(".deptselector").click(function(e) {
            e.stopImmediatePropagation();
            $(this).closest($('li')).find('input:checkbox').attr('checked', this.checked);
            // parseUserSelectors();
        });
        $(".userselector").click(function() {
            // parseUserSelectors();
        });
        if ( $.browser.msie ){
			$("#logo").css('padding-top','0px');
			$("#logo").css('margin-top','31px');
			$("#main_menu").css('padding-left','15px');
			$("#user_access").css('padding-right','15px');
			$("#user_access").css('margin-top','8px');
			$(".help_links").css('width','230px');
		}
    });
    
    var parseUserSelectors = function() {
        var userFilters = [];
        $(".userselector:checked").each(function() {
            userFilters.push($(this).attr('id'));
        });

        return userFilters;
    };
</script>

