<?php if (!empty($this->moduleContactDetails)): ?>
    <?php echo $this->moduleContactDetails['product_address']; ?><br/>
    <?php echo $this->moduleContactDetails['product_postal_code']; ?> <?php echo $this->moduleContactDetails['product_city']; ?><br/>
    T <?php echo $this->moduleContactDetails['product_tel']; ?><br/>
    <?php echo $this->moduleContactDetails['product_www']; ?><br/>
<?php endif; ?>